import img from "./assets/laptop.webp";
const allCourses = [
  {
    id: 1,
    title: "React for Beginners",
    rating: 4.5,
    lecturer: "John Doe",
    description: "Learn the basics of React.",
    img: img,
    category: "Web Development",
  },
  {
    id: 2,
    title: "Advanced JavaScript",
    rating: 4.7,
    lecturer: "Jane Smith",
    description: "Deep dive into JavaScript.",
    img: img,
    category: "Web Development",
  },
  {
    id: 3,
    title: "Data Analysis with Python",
    rating: 4.8,
    lecturer: "Alice Brown",
    description: "Learn Data Analysis using Python.",
    img: img,
    category: "Data Science",
  },
  {
    id: 4,
    title: "CSS Mastery",
    rating: 4.5,
    lecturer: "Emily Davis",
    description: "Become an expert in CSS.",
    img: img,
    category: "Web Development",
  },
  {
    id: 5,
    title: "Machine Learning Essentials",
    rating: 1.9,
    lecturer: "Michael Lee",
    description: "Get started with Machine Learning.",
    img: img,
    category: "Data Science",
  },
  {
    id: 6,
    title: "Node.js for Backend",
    rating: 4.6,
    lecturer: "Sarah Green",
    description: "Build server-side apps with Node.js.",
    img: img,
    category: "Web Development",
  },
  {
    id: 7,
    title: "CSS Mastery",
    rating: 4.5,
    lecturer: "Emily Davis",
    description: "Become an expert in CSS.",
    img: img,
    category: "Web Development",
  },
  {
    id: 8,
    title: "Machine Learning Essentials",
    rating: 1.9,
    lecturer: "Michael Lee",
    description: "Get started with Machine Learning.",
    img: img,
    category: "Data Science",
  },
  {
    id: 9,
    title: "Node.js for Backend",
    rating: 4.6,
    lecturer: "Sarah Green",
    description: "Build server-side apps with Node.js.",
    img: img,
    category: "Web Development",
  },
];
export default allCourses;
